<a href="https://colab.research.google.com/github/Anuj-Agrawal-code/Py_libraries/blob/main/Numpy_SELF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40]) #1-D array
print("Array: \n",a)
print("Dimensions: ",a.ndim) #Returns no of dimensions
print("Shape: ",a.shape)
print("Size(Total no of elements): ", a.size)
print("Dtype(datatype used in array can be float, int etc.): ", a.dtype)
print("type(is it numpy array or not): ", type(a))
print("\n\n")



a = np.array([            #2-D array
    [10, 20, 30],
    [40, 50, 60]
])
print("Array: \n",a)
print("Dimensions: ",a.ndim) #Returns no of dimensions
print("Shape: ",a.shape)
print("Size(Total no of elements): ", a.size)
print("Dtype(datatype used in array can be float, int etc.): ", a.dtype)
print("type(is it numpy array or not): ", type(a))
print("\n\n")



a = np.array(             #3-D array
    [
        [[1,2,3],
         [4,5,6],
         [7,8,9]],

        [[11,12,13],
         [14,15,16],
         [17,18,19]]
    ]
)
print("Array: \n",a)
print("Dimensions: ",a.ndim) #Returns no of dimensions
print("Shape: ",a.shape)
print("Size(Total no of elements): ", a.size)
print("Dtype(datatype used in array can be float, int etc.): ", a.dtype)
print("type(is it numpy array or not): ", type(a))
print("\n\n")

Array: 
 [10 20 30 40]
Dimensions:  1
Shape:  (4,)
Size(Total no of elements):  4
Dtype(datatype used in array can be float, int etc.):  int64
type(is it numpy array or not):  <class 'numpy.ndarray'>



Array: 
 [[10 20 30]
 [40 50 60]]
Dimensions:  2
Shape:  (2, 3)
Size(Total no of elements):  6
Dtype(datatype used in array can be float, int etc.):  int64
type(is it numpy array or not):  <class 'numpy.ndarray'>



Array: 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
Dimensions:  3
Shape:  (2, 3, 3)
Size(Total no of elements):  18
Dtype(datatype used in array can be float, int etc.):  int64
type(is it numpy array or not):  <class 'numpy.ndarray'>





In [ ]:
print("a = np.arange(start, stop, step)")
print("Arrange(5): \n",np.arange(5))
print("Arrange(2,10): \n",np.arange(2, 10))
print("Arrange(2,11,2): \n",np.arange(2,11,2))
print("\n\n")

print("a.reshape(rows, columns)")
a = np.arange(1,13)
print("Original: \n",a)
print("Reshaped(3,4): \n",a.reshape(3,4))
print("\n\n")

a = np.arange(start, stop, step)
Arrange(5): 
 [0 1 2 3 4]
Arrange(2,10): 
 [2 3 4 5 6 7 8 9]
Arrange(2,11,2): 
 [ 2  4  6  8 10]



a.reshape(rows, columns)
Original: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped(3,4): 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]





In [ ]:
print("a = np.Zeros(shape of array you want, dtype = int(if you want because by default it gives float thats why a dot appers after each number in the output))")
a = np.zeros(4)
print("Array(4): \n",a)

a = np.zeros((4, 4),  dtype = int)
print("Array(4, 4, int): \n",a)
print("\n\n")



print("a = np.ones(shape of array you want, dtype = int(if you want because by default it gives float thats why a dot appers after each number in the output))")
a = np.ones(4)
print("Array(4): \n",a)

a = np.ones((4, 4), int)
print("Array(4, 4, int): \n",a)
print("\n\n")


print("a = np.full(shape of array you want, value you want to fill array with))")
a = np.full(4, 6)
print("Array(4, 6): \n",a)

a = np.full((4, 4), 7)
print("Array((4,4), 7): \n",a)
print("\n\n")


print("a = np.eye(no of \"1\" in diagonal){used to create identity matrix}")
a = np.eye(5)
print("Array(5): \n",a)
print("\n\n")

a = np.Zeros(shape of array you want, dtype = int(if you want because by default it gives float thats why a dot appers after each number in the output))
Array(4): 
 [0. 0. 0. 0.]
Array(4, 4, int): 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]



a = np.ones(shape of array you want, dtype = int(if you want because by default it gives float thats why a dot appers after each number in the output))
Array(4): 
 [1. 1. 1. 1.]
Array(4, 4, int): 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]



a = np.full(shape of array you want, value you want to fill array with))
Array(4, 6): 
 [6 6 6 6]
Array((4,4), 7): 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]



a = np.eye(no of "1" in diagonal){used to create identity matrix}
Array(5): 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]





In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("a + b or np.add(a, b): ", a + b)
print("a - b or np.subtract(a, b): ", a - b)
print("a * b or np.multiply(a, b): ", a * b)
print("a / b or np.divide(a, b): ", a / b)
print("a // b or np.floor_divide(a, b): ", a // b)
print("a % b or np.mod(a, b): ", a % b)
print("a ** b or np.power(a, b): ", a ** b)
print("\n\n")

c = np.array([-1.5, 2.718, 3.142])
print("Array c (for helper functions): ", c)
print("np.sqrt(a): ", np.sqrt(a))
print("np.exp(b){e ^ b(b can be an array or single digit)}: ", np.exp(b))
print("np.log(a){base: 2}: ", np.log(a))
print("np.log10(a){base : 10}: ", np.log10(a))
print("np.sin(b): ", np.sin(b))
print("np.cos(b): ", np.cos(b))
print("np.tan(b): ", np.tan(b))
print("np.round(c, 2(no of digit after decimal)) : ", np.round(c, 2))
print("np.floor(c): ", np.floor(c))
print("np.ceil(c): ", np.ceil(c))
print("np.abs(c){mod}: ", np.abs(c))
print("\n\n")


a + b or np.add(a, b):  [11 22 33]
a - b or np.subtract(a, b):  [ 9 18 27]
a * b or np.multiply(a, b):  [10 40 90]
a / b or np.divide(a, b):  [10. 10. 10.]
a // b or np.floor_divide(a, b):  [10 10 10]
a % b or np.mod(a, b):  [0 0 0]
a ** b or np.power(a, b):  [   10   400 27000]



Array c (for helper functions):  [-1.5    2.718  3.142]
np.sqrt(a):  [3.16227766 4.47213595 5.47722558]
np.exp(b){e ^ b(b can be an array or single digit)}:  [ 2.71828183  7.3890561  20.08553692]
np.log(a){base: 2}:  [2.30258509 2.99573227 3.40119738]
np.log10(a){base : 10}:  [1.         1.30103    1.47712125]
np.sin(b):  [0.84147098 0.90929743 0.14112001]
np.cos(b):  [ 0.54030231 -0.41614684 -0.9899925 ]
np.tan(b):  [ 1.55740772 -2.18503986 -0.14254654]
np.round(c, 2(no of digit after decimal)) :  [-1.5   2.72  3.14]
np.floor(c):  [-2.  2.  3.]
np.ceil(c):  [-1.  3.  4.]
np.abs(c){mod}:  [1.5   2.718 3.142]





In [ ]:
a = np.array([10, 20, 30])

print("np.mean(a): ", np.mean(a))
print("np.max(a): ", np.max(a))
print("np.min(a): ", np.min(a))
print("\n")


# Example 1: Low spread (values are very close to each other)
low_spread = np.array([10, 11, 12])
print("Low spread array: ", low_spread)
print("np.std(low_spread): ", np.std(low_spread))
print("\n")

# Example 2: High spread (values are far apart from each other)
high_spread = np.array([10, 50, 90])
print("High spread array: ", high_spread)
print("np.std(high_spread): ", np.std(high_spread))
print("\n\n")

np.mean(a):  20.0
np.max(a):  30
np.min(a):  10


Low spread array:  [10 11 12]
np.std(low_spread):  0.816496580927726


High spread array:  [10 50 90]
np.std(high_spread):  32.65986323710904





In [ ]:
scores = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [90, 95, 88]
])

print("np.mean(scores, axis = 0{for rows}): ", np.mean(scores, axis = 0))
print("np.mean(scores, axis = 1{for columns}): ", np.mean(scores, axis = 1))
print("\n\n")

np.mean(scores, axis = 0{for rows}):  [76.66666667 83.33333333 84.33333333]
np.mean(scores, axis = 1{for columns}):  [80.         73.33333333 91.        ]





In [ ]:
#Vectorization
a = np.array([10, 20, 30])
print("a: \n",a)
print("a + 5: \n", a + 5)
print("No need to use loops")
print("\n")


array = np.array([10, 20, 30, 40, 50])

max_value = np.max(array)

normalized_array = array / max_value

print("array: \n", array)
print("normalized_array(array/ max(array)): \n", normalized_array)
print("\n\n")


a: 
 [10 20 30]
a + 5: 
 [15 25 35]
No need to use loops


array: 
 [10 20 30 40 50]
normalized_array(array/ max(array)): 
 [0.2 0.4 0.6 0.8 1. ]





In [ ]:
import numpy.linalg as LA

A = np.array([
    [1, 2],
    [3, 4]
])

print("LA.det(matrix){Determinant value}: ",LA.det(A).round(2))
print("LA.inv(matrix){Inverse of matrix}: \n",LA.inv(A))
eigenvalues, eigenvectors = LA.eig(A)
print("LA.eig(matrix)\n {Eigenvalues}: \n",eigenvalues, "\n {eigenvectors}: \n", eigenvectors)
print("\n\n")



LA.det(matrix){Determinant value}:  -2.0
LA.inv(matrix){Inverse of matrix}: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
LA.eig(matrix)
 {Eigenvalues}: 
 [-0.37228132  5.37228132] 
 {eigenvectors}: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]





In [ ]:
print("Ax = b")
print("x = A^{-1} b")
print("solve for x, y in system of equations")
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([8, 9])

x = LA.solve(A, b)
print("Value for x, y(LA.solve(A, b)): ", x)

Ax = b
x = A^{-1} b
solve for x, y in system of equations
Value for x, y(LA.solve(A, b)):  [3. 2.]
